project:
  type: book
  output-dir: _book

site-url: https://urbandesigntudelft.github.io/ouagb-m/
base-url: /ouagb-m/

book:
  title: "Open Urban Analysis Guidebook: Morphology"
  author:
    - name: Giambattista Nolli
      orcid: 0000-0003-1689-0557
      email: bill@gates.com
      affiliations:
        - name: The Morphology Foundation
          city: Rome
  date: "10/23/2025"
  chapters:
    - index.qmd
    - chapters/foundations_frontiers.qmd
    - part: "Methodology, Techniques & Applications"
      chapters:
        - chapters/methodology.qmd
        - chapters/techniques.qmd
        - chapters/applications.qmd
        - chapters/quiz.Rmd
    - part: "Cases"
      chapters:
        - catalog/index.qmd
        - catalog/examples/roma_al_tempo_di_benedetto.qmd
        - catalog/examples/Stadtebau.qmd
        - catalog/examples/ville_radieuse.qmd
        - catalog/examples/studi_per_una_operante.qmd
        - catalog/examples/image_of_the_city.qmd
        - catalog/examples/concise_townscape.qmd
        - catalog/examples/las_vegas.qmd
        - catalog/examples/bologna.qmd
        - catalog/examples/comparisons_of_form_and_scale.qmd
        - catalog/examples/collage_city.qmd
        - catalog/examples/elements_urbaine.qmd
        - catalog/examples/versailles.qmd
        - catalog/examples/stedelijk_bouwwerk.qmd
        - catalog/examples/les_bastides.qmd
        - catalog/examples/built_for_change.qmd
        - catalog/examples/verstedelijkt_landschap.qmd
        - catalog/examples/locatie_zuidpoortgebied.qmd
        - catalog/examples/la_metropole_imaginaire.qmd
        - catalog/examples/landschap_en_verstedelijking.qmd
        - catalog/examples/gli_orizzonti.qmd
        - catalog/examples/point_city.qmd
        - catalog/examples/paris_des_faubourgs.qmd
        - catalog/examples/porto_the_breakthrough.qmd
        - catalog/examples/colonial_settlements.qmd
        - catalog/examples/het_land_in_de_stad.qmd
        - catalog/examples/stadsportretten.qmd
        - catalog/examples/zee_van_land.qmd
        - catalog/examples/bindels_gietema.qmd
        - catalog/examples/costa_iberica.qmd
        - catalog/examples/een_nieuwe_oude_jas.qmd
        - catalog/examples/after_sprawl.qmd
        - catalog/examples/belvedere_bouwen.qmd
        - catalog/examples/city_branding.qmd
        - catalog/examples/ijburg.qmd
        - catalog/examples/mobility.qmd
        - catalog/examples/haarlemmermeer.qmd
        - catalog/examples/evolution_of_a_compact_city.qmd
        - catalog/examples/measuring_pompeii.qmd
        - catalog/examples/object_van_beweging.qmd
        - catalog/examples/the_view_from_the_road.qmd
        - catalog/examples/kumbh_mela.qmd
        - catalog/examples/territory_of_a_new_modernity.qmd
        - catalog/examples/building_with_superblocks.qmd
        - catalog/examples/manifolds_grids.qmd
        - catalog/examples/grassroots_mapping.qmd
        - catalog/examples/favelas_4d.qmd
        - catalog/examples/glastonbury.qmd
        - catalog/examples/kobe_refugee_camp.qmd
        - catalog/examples/mapping_wuhan.qmd
    - part: "Appendices"
      chapters:
        # - appendices/glossary.qmd
        - appendices/references.qmd

  page-footer:
    center: "Â© 2025, Section of Urban Design TU Delft - CC BY 4.0"

license: "CC BY"

bibliography: references.bib

format:
  html:
    theme:
      - journal    # alternative: cosmo, yeti, lux, flatly, journal
      - brand
    toc: true
    lightbox: true
    number-sections: true
    smooth-scroll: true
    anchor-sections: true
    fig-cap-location: margin
    tbl-cap-location: top
    bread-crumbs: false
    css: styles.css
  # pdf:
  #   documentclass: scrreprt

# Enable site-wide search
search: true

# Speed up rebuilds in CI
execute:
  freeze: auto
