project:
  type: book
  output-dir: _book

site-url: https://urbandesigntudelft.github.io/ouagb-m/
base-url: /ouagb-m/

book:
  title: "Open Urban Analysis Guidebook: Morphology"
  author:
    - name: Giambattista Nolli
      orcid: 0000-0003-1689-0557
      email: bill@gates.com
      affiliations:
        - name: The Morphology Foundation
          city: Rome
  date: "10/23/2025"
  chapters:
    - index.qmd
    - chapters/foundations_frontiers.qmd
    - part: "Methodology, Techniques & Applications"
      chapters:
        - chapters/methodology.qmd
        - chapters/techniques.qmd
        - chapters/applications.qmd
    - part: "Cases"
      chapters:
        - catalog/index.qmd
        - catalog/examples/roma_al_tempo_di_benedetto.qmd
        - catalog/examples/image_of_the_city.qmd
        - catalog/examples/01.qmd
    - part: "Appendices"
      chapters:
        # - appendices/glossary.qmd
        - appendices/references.qmd

  page-footer:
    center: "Â© 2025, Section of Urban Design TU Delft - CC BY 4.0"

license: "CC BY"

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true
    smooth-scroll: true
    anchor-sections: true
    fig-cap-location: margin
    tbl-cap-location: top
    bread-crumbs: false
    css: styles.css
  # pdf:
  #   documentclass: scrreprt

# Enable site-wide search
search: true

# Speed up rebuilds in CI
execute:
  freeze: auto
